//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRecruitmentCell
    {
        public int ID { get; set; }
        public string Type { get; set; }
        public string SubType { get; set; }
        public string Title { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public string FileType { get; set; }
        public Nullable<int> FileSize { get; set; }
        public string ExamDescription { get; set; }
        public Nullable<int> NoofPosts { get; set; }
        public Nullable<System.DateTime> LastDateofApplication { get; set; }
        public string AdvertisementsNo { get; set; }
        public string URL { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public Nullable<bool> IsPublished { get; set; }
        public Nullable<System.DateTime> IsPublishedDate { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public Nullable<System.DateTime> IsArchivedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
